[loggers]
keys=root, ledController, actionListener

[handlers]
keys=lumosFileHandler

[formatters]
keys=mainFormatter

[logger_root]
level=INFO
handlers=lumosFileHandler
qualname=lumos
propagate=0

[logger_ledController]
level=INFO
handlers=lumosFileHandler
qualname=lumos.led_controller
propagate=0

[logger_actionListener]
level=INFO
handlers=lumosFileHandler
qualname=lumos.action_listener
propagate=0

[handler_lumosFileHandler]
class=FileHandler
level=INFO
formatter=mainFormatter
args=("%(logfile)s", "w")

[formatter_mainFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=
